// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP5vOpzMhzAaYtq6U-Q-kuLcnjBIZo5J4',
    appId: '1:360454526534:web:025c2dfbca04cfa1f3dc47',
    messagingSenderId: '360454526534',
    projectId: 'carros-64916',
    authDomain: 'carros-64916.firebaseapp.com',
    storageBucket: 'carros-64916.appspot.com',
    measurementId: 'G-KSC7Q2WJ3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3MQD-s9heDoiFuwkmJiOLBvFrhg1vsGs',
    appId: '1:360454526534:android:0c165e34ff94151cf3dc47',
    messagingSenderId: '360454526534',
    projectId: 'carros-64916',
    storageBucket: 'carros-64916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-BB3f7u8wFXkjCM9bWxVB2dwV59iXL34',
    appId: '1:360454526534:ios:63655e02a5c6b348f3dc47',
    messagingSenderId: '360454526534',
    projectId: 'carros-64916',
    storageBucket: 'carros-64916.appspot.com',
    iosClientId: '360454526534-hf23ujm591e3nbq6mugvmkao8hcgqp7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-BB3f7u8wFXkjCM9bWxVB2dwV59iXL34',
    appId: '1:360454526534:ios:63655e02a5c6b348f3dc47',
    messagingSenderId: '360454526534',
    projectId: 'carros-64916',
    storageBucket: 'carros-64916.appspot.com',
    iosClientId: '360454526534-hf23ujm591e3nbq6mugvmkao8hcgqp7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
